### ISSUE TITLE
emscripten_get_canvas_element_size() not returning correct values

### ISSUE THREAD

**Issue by raysan5** [emscripten-core/emscripten#10285]
I needed to retrieve canvas size to scale touch inputs for a CSS scaled canvas:
```css
canvas.emscripten { 
    border: 0px none; 
    background: black; 
    width: 100% 
}
```
I tried using `emscripten_get_canvas_element_size()`:
```c
int canvasWidth, canvasHeight;
EMSCRIPTEN_RESULT res = emscripten_get_canvas_element_size("#canvas", &canvasWidth, &canvasHeight);
```
but despite the canvas being scaled with the browser, it always returns contained framebuffer size.

To solve this issue I used instead `emscripten_get_element_css_size()`:
```c
double canvasWidth, canvasHeight, fs;
EMSCRIPTEN_RESULT res = emscripten_get_element_css_size("#canvas", &canvasWidth, &canvasHeight);
```
And it worked as expected.
