### ISSUE TITLE
How to properly load SIDE_MODULE from MAIN_MODULE in Emscripten?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11507]
Hi, I'm trying to create a simple example using `MAIN_MODULE/SIDE_MODULE` based on https://github.com/emscripten-core/emscripten/wiki/Linking#general-dynamic-linking but cannot make it work.

Here's my code:

**main.c:**

```
#include <stdio.h>
 
int side(int a);
 
int main()
{
    printf("hello world %d\n", side(1));
}
```
**side.c:**
```
int side(int a)
{
    return a + 1;
}
```
**compile:**
```
emcc side.c -s SIDE_MODULE=1 -o side.wasm
emcc main.c -s MAIN_MODULE=1 -o main.html
```
**index.html**
```
<!DOCTYPE html>
<html>

<head>
</head>

<body>
  <script>
    var Module
      = {
      preRun: []
      , postRun: []
      , print: function (e) {
        1 < arguments.length && (e = Array.prototype.slice.call(arguments).join(" "));
        console.log(e);
      }
      , printErr: function (e) {
        1 < arguments.length && (e = Array.prototype.slice.call(arguments).join(" "));
        console.error(e)
      }
    };
    Module.dynamicLibraries = ['side.wasm'];
  </script>
  <script async src="main.js"></script>
</body>

</html>
```
If I run it with `python -m SimpleHTTPServer`, I get the following errors:

```
(index):19 Assertion failed: undefined
printErr @ (index):19
abort @ main.js:33157
assert @ main.js:1074
removeRunDependency @ main.js:1984
(anonymous) @ main.js:2274
Promise.then (async)
instantiateArrayBuffer @ main.js:2272
(anonymous) @ main.js:2301
Promise.then (async)
(anonymous) @ main.js:2296
Promise.then (async)
instantiateAsync @ main.js:2288
createWasm @ main.js:2321
Module.asm @ main.js:2344
(anonymous) @ main.js:31495
(index):19 failed to asynchronously prepare wasm: abort(Assertion failed: undefined) at Error
    at jsStackTrace (http://localhost:8000/main.js:1626:13)
    at stackTrace (http://localhost:8000/main.js:1643:12)
    at abort (http://localhost:8000/main.js:33163:44)
    at assert (http://localhost:8000/main.js:1074:5)
    at removeRunDependency (http://localhost:8000/main.js:1984:5)
    at http://localhost:8000/main.js:2274:7
```

Any advice or guidance would be greatly appreciated!

**Comment by sbc100** [comment]
I can't see what it wrong off the bat.

Try specifying the module on the command line via `RUNTIME_LINKED_LIBS=['side.wasm']`,   then you should be able to use the generated main.html rather than writing your own.

**Comment by cuinjune** [comment]
It still gives me the same error even when I compile the main module with `emcc main.c -s MAIN_MODULE=1 -s RUNTIME_LINKED_LIBS="['side.wasm']" -o main.html`

**Comment by sbc100** [comment]
Works for me.  Can you try these exact steps:

```
$ emcc side.c -s SIDE_MODULE=1 -o side.wasm
$ emcc main.c -s MAIN_MODULE=1 -o main.html -s "RUNTIME_LINKED_LIBS=['side.wasm']"
$ node ./main.js
hello world 2
```

**Comment by sbc100** [comment]
Maybe something to do with how you are hosting you modules?   How are you serving the html and wasm modules?  Are you using emrun?

**Comment by cuinjune** [comment]
@sbc100 I used `python -m SimpleHTTPServer` to host on localhost.

When I try exactly the same steps as you wrote, I get the following error in Terminal console after the last step:

> external function 'side' is missing. perhaps a side module was not linked in? if this function was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment
> external function 'side' is missing. perhaps a side module was not linked in? if this function was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment
> exception thrown: abort(external function 'side' is missing. perhaps a side module was not linked in? if this function was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment) at Error
>     at jsStackTrace (/Users/cuinjune/Desktop/module_test/main.js:1626:13)
>     at stackTrace (/Users/cuinjune/Desktop/module_test/main.js:1643:12)
>     at abort (/Users/cuinjune/Desktop/module_test/main.js:33165:44)
>     at _side (/Users/cuinjune/Desktop/module_test/main.js:8492:25)
>     at wasm-function[143]:32
>     at Object.Module._main (/Users/cuinjune/Desktop/module_test/main.js:32403:33)
>     at Object.callMain (/Users/cuinjune/Desktop/module_test/main.js:33003:30)
>     at doRun (/Users/cuinjune/Desktop/module_test/main.js:33061:60)
>     at run (/Users/cuinjune/Desktop/module_test/main.js:33075:5)
>     at runCaller (/Users/cuinjune/Desktop/module_test/main.js:32982:29)

**Comment by sbc100** [comment]
You might need to add some debugging to find out what is going on.

Can you run one of the dynamic linking tests. e.g.:

`./tests/runner.py wasm2g.test_dylink_basics`

**Comment by sbc100** [comment]
Can you run `wasm-objdump -x side.wasm` to see what the side module looks like?   You should see `side` being exported.

What version of emscripten are you using?

**Comment by cuinjune** [comment]
@sbc100 Thank you for your suggestions. I tried everything but could not make it work.
I also posted this on https://stackoverflow.com/q/62587188/5224286

I would appreciate it if anyone has any suggestions.

**Comment by sbc100** [comment]
What is the result when you run `./tests/runner.py wasm2g.test_dylink_basics`

**Comment by cuinjune** [comment]
@sbc100 Here's the result I get:

```
./tests/runner.py:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
test_dylink_basics (test_core.wasm2g) ... flip
ok

----------------------------------------------------------------------
Ran 1 test in 8.813s

OK
```

**Comment by sbc100** [comment]
It looks like the `RUNTIME_LINKED_LIBS` is somehow not working correctly.. can you verify that you passing that option when you build your main module?  

Perhaps also verify that the side module does contains `side` export (you can use wasm-dis or wasm2wat tools to do this).

**Comment by cuinjune** [comment]
@sbc100 I already tried `emcc main.c -s MAIN_MODULE=1 -o main.html -s "RUNTIME_LINKED_LIBS=['side.wasm']"` which didn't work.

I don't know how to verify that the side module does contain side export. I would appreciate a more specific guide to do it.

**Comment by sbc100** [comment]
You can use `wasm-objdump -x side.wasm` to take a look at the side module .. then see if `side` is listed as an export.

the location of `wasm-objdump` should be alongside clang (in emsdk that means something like `emsdk/upstream/bin`)

**Comment by cuinjune** [comment]
Thanks, here's what I got:

```
side.wasm:	file format wasm 0x1

Section Details:

Custom:
 - name: "dylink"
 - mem_size     : 5243056
 - mem_p2align  : 4
 - table_size   : 0
 - table_p2align: 0
Type[5]:
 - type[0] (i32) -> nil
 - type[1] (i32) -> i32
 - type[2] () -> i32
 - type[3] (i32, i32) -> nil
 - type[4] () -> nil
Import[9]:
 - func[0] sig=0 <env.abortStackOverflow> <- env.abortStackOverflow
 - global[0] i32 mutable=0 <- env.__memory_base
 - global[1] i32 mutable=0 <- env.__table_base
 - global[2] i32 mutable=0 <- env.tempDoublePtr
 - global[3] i32 mutable=0 <- env.DYNAMICTOP_PTR
 - global[4] f64 mutable=0 <- global.NaN
 - global[5] f64 mutable=0 <- global.Infinity
 - memory[0] pages: initial=256 <- env.memory
 - table[0] elem_type=funcref init=0 max=0 <- env.table
Function[6]:
 - func[1] sig=1
 - func[2] sig=2
 - func[3] sig=0
 - func[4] sig=3
 - func[5] sig=1
 - func[6] sig=4 <__post_instantiate>
Global[16]:
 - global[6] i32 mutable=1 - init global=2 <env.tempDoublePtr>
 - global[7] i32 mutable=1 - init global=3 <env.DYNAMICTOP_PTR>
 - global[8] i32 mutable=1 - init i32=0
 - global[9] i32 mutable=1 - init i32=0
 - global[10] i32 mutable=1 - init i32=0
 - global[11] i32 mutable=1 - init i32=0
 - global[12] i32 mutable=1 - init i32=0
 - global[13] i32 mutable=1 - init i32=0
 - global[14] i32 mutable=1 - init i32=0
 - global[15] i32 mutable=1 - init i32=0
 - global[16] i32 mutable=1 - init i32=0
 - global[17] f64 mutable=1 - init f64=0x0p+0
 - global[18] f64 mutable=1 - init global=4 <global.NaN>
 - global[19] f64 mutable=1 - init global=5 <global.Infinity>
 - global[20] f32 mutable=1 - init f32=0x0p+0
 - global[21] f32 mutable=1 - init f32=0x0p+0
Export[1]:
 - func[6] <__post_instantiate> -> "__post_instantiate"
Code[6]:
 - func[1] size=40
 - func[2] size=5
 - func[3] size=6
 - func[4] size=10
 - func[5] size=49
 - func[6] size=19 <__post_instantiate>

```
