### ISSUE TITLE
windows 10 emsdk.ps1 install latest returns error

### ISSUE THREAD

**Issue by richardlalancette** [emscripten-core/emscripten#15049]
![image](https://user-images.githubusercontent.com/1323032/133498558-95febebd-09a7-43c6-8e7e-93eaec23bfc8.png)

![image](https://user-images.githubusercontent.com/1323032/133499234-79b3d78b-e89a-4c2e-8858-ca4e2ded99be.png)

**Comment by richardlalancette** [comment]
Oh, but seems to work via Github actions. Interesting...

```
name: Build wasm based imgui POC
on: [push]

jobs:
  setup-emscripten:
    runs-on: windows-latest
    name: Setup emscripten
    steps:
      - name: pre-setup
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test emscripten
        run: |
          emsdk/emsdk install latest
          emsdk/emsdk activate latest
          emsdk/emsdk_env.ps1 
          make -C docs
        
```
