### ISSUE TITLE
Emscripten error about `dlopen` despite that function being unused and no other links being used

### ISSUE THREAD

**Issue by Frityet** [emscripten-core/emscripten#16645]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```yaml
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.7-git
clang version 15.0.0 (https://github.com/llvm/llvm-project.git fbce4a78035c32792b0a13cf1f169048b822c06b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/Cellar/emscripten/3.1.7/libexec/llvm/bin
```

**Failing command line in full:**
`Aborted(To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking)`

**Full link command and output with `-v` appended:**
https://gist.github.com/Frityet/4f225acd871bb632929424f3145a91ff
