### ISSUE TITLE
register_vector from version 3.1.54 onwards no longer works with get()

### ISSUE THREAD

**Issue by Carl-Hughes-Orthrus** [emscripten-core/emscripten#21724]
Since I have upgraded from 3.1.53 to 3.1.54 I can no longer use the registered vector class correctly to get values.

I was originally exporting bindings as:

```
//
// Created by carl.hughes on 07/04/2022.
//
#include <emscripten/bind.h>
using namespace emscripten;

std::vector<double> dummy_results (){
    return {1.0, 2.0, 3.0};
}

EMSCRIPTEN_BINDINGS(particle_track_reader) {
    function("dummy_results", &dummy_results);
    register_vector<char>("VectorChar");
    register_vector<double>("VectorDouble");
}
```

then in js:
```
let dummy_results = module.dummy_results()
then convert it to a standard JS array by:
dummy_results = Array.from({ length: dummy_results .size() }, (_, id) => dummy_results .get(id));
```
but it fails to do the conversion as the get method no longer works:
![image](https://github.com/emscripten-core/emscripten/assets/161612294/0d3dcb7d-2638-4de0-b72a-d37b2081858d)

from console logging the vector:
```
ClassHandle {$$: {…}}
    $$: 
        count: {value: 1}
        ptr: 15136368
        ptrType: RegisteredPointer {name: 'VectorDouble*', registeredClass: RegisteredClass, isReference: false, isConst: false, isSmartPointer: false, …}
        [[Prototype]]: Object
    [[Prototype]]: ClassHandle
        get: ƒ unboundTypesHandler()
        push_back: ƒ (arg0)
        resize: ƒ (arg0, arg1)
        set: ƒ (arg0, arg1)
        size: ƒ ()
        constructor: ƒ (...args)
        [[Prototype]]: Object
```        
Its treating get as an unboundTypesHandler where it should be returning a double

Can someone explain what has changed to cause this?

I haven't had this issue prior to upgrading to 3.1.54.
